name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: "0.1.0"

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  pagination_view: ^2.0.0-nullsafety.0
  faker: ^2.2.0
  provider: ^6.1.5+1
  graphic: ^2.6.0
  fl_chart: ^1.0.0
  smooth_page_indicator: ^1.2.1
  openfoodfacts: ^3.25.1
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: IstokWeb
      fonts:
        - asset: assets/fonts/IstokWeb-Regular.ttf
  assets:
    # JSON Data Files
    - assets/data/default_exercises.json
    - assets/data/default_muscles.json
    - assets/data/default_foods.json
    - assets/data/usda_foundation_foods.json

    # SVG Icons
    - assets/svg/lucide--dumbbell.svg
    - assets/svg/mdi--food-apple-outline.svg
    - assets/svg/material-symbols--target.svg
    - assets/svg/game-icons--progression.svg
    - assets/svg/ri--calendar-schedule-fill.svg
    - assets/svg/material-symbols--settings.svg
    - assets/svg/bxs--widget.svg
    - assets/svg/food--not--found.svg
    - assets/svg/streamline--return-2-solid.svg
    - assets/svg/ic--round-plus.svg
    - assets/svg/material-symbols--trophy-outline.svg
    - assets/svg/mdi--calendar.svg
    - assets/svg/streamline-plump--dumbell-solid.svg
    - assets/svg/emojione-monotone--fork-and-knife-with-plate.svg
    - assets/svg/material-symbols--barcode.svg
    - assets/svg/mdi--filter.svg
    - assets/svg/entypo--magnifying-glass.svg
    - assets/svg/solar_dumbbell-small-bold-duotone.svg
    - assets/svg/emojione_fork-and-knife.svg
