name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 
version: "0.1.0"

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  pagination_view: ^2.0.0-nullsafety.0
  faker: ^2.2.0
  provider: ^6.1.5+1
  graphic: ^2.6.0
  fl_chart: ^1.0.0
  smooth_page_indicator: ^2.0.1
  openfoodfacts: ^3.25.1
  sqflite: ^2.4.2
  path: ^1.9.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
    - family: IstokWeb
      fonts:
        - asset: assets/fonts/IstokWeb-Regular.ttf
  assets:
    # JSON Data Files
    - assets/data/

    # SVG Icons
    - assets/svg/

    # Exercise Images
    - assets/exercises/
