// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkVWcztyQwv-h6M2iEyyVOavBx5SEoPx0',
    appId: '1:526881114599:web:8bee90605c4d988f075542',
    messagingSenderId: '526881114599',
    projectId: 'myproject2374728',
    authDomain: 'myproject2374728.firebaseapp.com',
    storageBucket: 'myproject2374728.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLEX3YephHvfYFT4k2BnkjD9J6FdSrgw',
    appId: '1:526881114599:android:97b2c4d643021dd4075542',
    messagingSenderId: '526881114599',
    projectId: 'myproject2374728',
    storageBucket: 'myproject2374728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0-IBXD9HYQVucQozaiNB8B6nmZdkKSvs',
    appId: '1:526881114599:ios:866d88c1ca0b2f08075542',
    messagingSenderId: '526881114599',
    projectId: 'myproject2374728',
    storageBucket: 'myproject2374728.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0-IBXD9HYQVucQozaiNB8B6nmZdkKSvs',
    appId: '1:526881114599:ios:866d88c1ca0b2f08075542',
    messagingSenderId: '526881114599',
    projectId: 'myproject2374728',
    storageBucket: 'myproject2374728.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkVWcztyQwv-h6M2iEyyVOavBx5SEoPx0',
    appId: '1:526881114599:web:eebff1ff7984b072075542',
    messagingSenderId: '526881114599',
    projectId: 'myproject2374728',
    authDomain: 'myproject2374728.firebaseapp.com',
    storageBucket: 'myproject2374728.firebasestorage.app',
  );
}
